config/routes.rb
Rails.application.routes.draw do

  get 'admin/show_product/:id', to: 'admin#show_product' , as: 'admin_product_show'
  get 'admin/edit_product/:id', to: 'admin#edit_product' , as: 'admin_product_edit'

  get 'admin/new_product', to: 'admin#new_product' , as: 'admin_product_new'

  get 'admin/show_order/:id', to: 'admin#show_order' , as: 'admin_order_show'

  get 'admin/show_user/:id', to: 'admin#show_user' , as: 'admin_user_show'

  get 'errors/404'

  get 'errors/500'

  get 'errors/403'

  get 'admin/index'

  get 'admin/products'

  get 'admin/users'

  get 'admin/orders'

  get 'home/index'

  get 'home/about'

  get 'store/index'

  resources :products

  resources :orders

  resources :line_items

  resources :carts

  root :to => 'home#index'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :products do
    get :who_bought, on: :member
  end

end

app/views/admin/edit_product.html.erb
<% if user_signed_in? %>
    <% if current_user.admin==1 %>
        <ol class="breadcrumb">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Amministrazione", admin_index_path %></li>
          <li><%= link_to "Prodotti", admin_products_path %></li>
          <li><%= link_to @product.title, admin_product_show_path(@product) %></li>
          <li class="active"><%= @product.title %> Edit</li>
        </ol>
        <h2 align="center">Gestione Prodotti</h2>
        <div class="row">
          <div class="col-md-8">
            <p class="lead">Modifica Dettagli prodotto
            </p>
          </div>

        </div>
        <div class="container">
          <p class="lead">Prodotto</p>


          <div class="row">
            <div class="col-md-8"><p>
              <%= form_for(@product) do |f| %>
                  <% if @product.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being
                          saved:</h2>

                        <ul>
                          <% @product.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                          <% end %>
                        </ul>
                      </div>
                  <% end %>
                  <div class="row">
                    <div class="col-md-4">
                      <div class="input-group">
                        <%= f.label :title %>
                        <br>
                        <%= f.text_field :title, :class => 'form-control' %>
                      </div>
                    </div>

                    <div class="col-md-4">
                      <div class="input-group">
                        <%= f.label :price %>

                        <%= f.text_field :price, :class => 'form-control' %>
                      </div>


                    </div>
                    <div class="col-md-4">
                      <div class="input-group">
                        <%= f.label :image_url %>
                        <br>
                        <%= f.text_field :image_url, :class => 'form-control' %>
                      </div>
                    </div>

                  </div>

                  <div class="field">
                    <%= f.label :description %>
                    <br>
                    <%= f.text_area :description, :class => 'form-control', :rows => 4 %>
                  </div>


                  <div class="actions">
                    <br>
                    <%= f.submit 'Salva', :class => 'btn btn-primary btn-xm' %>
                  </div>
              <% end %>



              <br>

              <div class="container">
                <%= link_to 'Show', admin_product_show_path(@product), :class => "btn btn-success btn-xs" %>
                <%= link_to 'Back', admin_products_path, :class => "btn btn-default btn-xs" %>
              </div>


            </div>
            <div class="col-md-4"></div>

          </div>


        </div>

    <% else %>
        <script type="text/javascript">
            window.location.href = "../errors/404"  // put your correct path in a string here
        </script>
    <% end %>
<% else %>
    <script type="text/javascript">
        window.location.href = "../errors/404"  // put your correct path in a string here
    </script>
<% end %>

app/views/admin/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li class="active">Amministrazione</li>
</ol>
<h2 align="center">Amministrazione</h2>
<div class="row">
  <div class="col-md-8">
    <p class="lead">Benvenuto nel pannello di Amministrazione di Europasport<br>
      Qui puoi gestire gli ordini i prodotti e gli utenti
    </p>

    <div class="container">
      <p class="lead">
        Statistiche shop
      </p>

      <p>

      <ul class="nav nav-pills" role="tablist">
        <li role="presentation"><a href=<%= admin_orders_path %>>Ordini <span class="badge"><%= @ordersNum %></span></a>
        </li>
        <li role="presentation">
          <a href=<%= admin_products_path %>>Prodotti <span class="badge"><%= @prodNum %></span></a></li>
        <li role="presentation"><a href=<%= admin_users_path %>>Utenti <span class="badge"><%= @usersNum %></span></a>
        </li>
      </ul>

      </p>

    </div>

  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <ul class="list-group">
          <li class="list-group-item btn-default"><%= link_to "Prodotti", admin_products_path %></li>
          <li class="list-group-item btn-default"><%= link_to "Utenti", admin_users_path %></li>
          <li class="list-group-item btn-default"><%= link_to "Ordini", admin_orders_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/admin/new_product.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Amministrazione", admin_index_path %></li>
  <li><%= link_to "Prodotti", admin_products_path %></li>
  <li class="active">Inserimento nuovo prodotto</li>
</ol>
<h2 align="center">Gestione Prodotti</h2>
<div class="row">
  <div class="col-md-8">
    <p class="lead">Nuovo Prodotto
    </p>
  </div>

</div>
<div class="container">
  <p class="lead">Prodotto</p>


  <div class="row">
    <div class="col-md-8"><p>
      <%= form_for(@product) do |f| %>
          <% if @product.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being
                  saved:</h2>

                <ul>
                  <% @product.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
          <div class="row">
            <div class="col-md-4">
              <div class="input-group">
                <%= f.label :title %>
                <br>
                <%= f.text_field :title, :class => 'form-control' %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="input-group">
                <%= f.label :price %>

                <%= f.text_field :price, :class => 'form-control' %>
              </div>


            </div>
            <div class="col-md-4">
              <div class="input-group">
                <%= f.label :image_url %>
                <br>
                <%= f.text_field :image_url, :class => 'form-control' %>
              </div>
            </div>

          </div>

          <div class="field">
            <%= f.label :description %>
            <br>
            <%= f.text_area :description, :class => 'form-control', :rows => 4 %>
          </div>


          <div class="actions">
            <br>
            <%= f.submit 'Salva', :class => 'btn btn-primary btn-xm' %>
          </div>
      <% end %>



      <br>

      <div class="container">
        <%= link_to 'Back', admin_products_path, :class => "btn btn-default btn-xs" %>
      </div>


    </div>
    <div class="col-md-4"></div>

  </div>


</div>

app/views/admin/orders.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Amministrazione", admin_index_path %></li>
  <li class="active">Ordini</li>
</ol>
<h2 align="center">Gestione Ordini</h2>
<div class="row">
  <div class="col-md-8">
    <p class="lead">Benvenuto nella pagina di gestione degli ordini
    </p>
  </div>

</div>


<div class="container">
  <p class="lead">Ordini</p>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Nome</th>
      <th>Indirizzo</th>
      <th>Email</th>
      <th>Tipo Pagamento</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @orders.each do |order| %>
        <tr>
          <td><%= order.name %></td>
          <td><%= order.address %></td>
          <td><%= order.email %></td>
          <td><%= order.pay_type %></td>
          <td><%= link_to 'Show', admin_order_show_path(order), :class => "btn btn-primary btn-xs" %></td>
          <td><%= link_to 'Destroy', order, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger btn-xs" %></td>

        </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/admin/products.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Amministrazione", admin_index_path %></li>
  <li class="active">Prodotti</li>
</ol>
<h2 align="center">Gestione Prodotti</h2>
<div class="row">
  <div class="col-md-8">
    <p class="lead">Benvenuto nella pagina di gestione dei prodotti
    </p>
  </div>

</div>


<div class="container">
  <p class="lead">Prodotti</p>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Titolo</th>
      <th>Descrizione</th>
      <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>
    <% @products.each do |product| %>
        <tr>
          <td><%= product.title %></td>
          <td><%= truncate(strip_tags(product.description), length: 80) %></td>
          <td><%= link_to 'Show', admin_product_show_path(product), :class => "btn btn-primary btn-xs" %></td>
          <td><%= link_to 'Edit', admin_product_edit_path(product), :class => "btn btn-success btn-xs" %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger btn-xs" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>


  <%= link_to 'New product', admin_product_new_path, :class => "btn btn-default btn-xs" %>

</div>

app/views/admin/show_order.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Amministrazione", admin_index_path %></li>
  <li><%= link_to "Ordine", admin_orders_path %></li>
  <li class="active">N°<%= @order.id %></li>
</ol>
<h2 align="center">Gestione Ordini</h2>
<div class="row">
  <div class="col-md-8">
    <p class="lead">Dettagli ordine
    </p>
  </div>

</div>
<div class="container">
  <p class="lead">Ordine N°: <%= @order.id %></p>


  <div class="row">
    <div class="col-md-8">
      <div class="container">

        <p class="row">
          <strong>Utente:</strong>
          <%= @user.name %>
        </p>


        <p class="row">
          <strong>Data ordine:</strong>
          <%= @order.updated_at %>
        </p>


        <p class="row">
          <strong>Nome:</strong>
          <%= @order.name %>
        </p>

        <p class="row">
          <strong>Indirizzo:</strong>
          <%= @order.address %>
        </p>

        <p class="row">
          <strong>Email:</strong>
          <%= @order.email %>
        </p>

        <p class="row">
          <strong>Tipo pagamento:</strong>
          <%= @order.pay_type %>
        </p>

        <div class="row">
          <div class="col-md-6">
            <ul class="list-group">
              <% @line_items.each do |line_item| %>
                  <li class="list-group-item">

                    <span class="badge"><%= line_item.quantity %></span>
                    <%= line_item.product.title %>
                  </li>
              <% end %>
            </ul>
          </div>
          <div class="col-md-6"></div>
        </div>


      </div>

      <%= link_to 'Indietro', admin_orders_path, :class => "btn btn-default btn-xs" %>
    </div>
    <div class="col-md-4"></div>
  </div>


</div>

app/views/admin/show_product.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Amministrazione", admin_index_path %></li>
  <li><%= link_to "Prodotti", admin_products_path %></li>
  <li class="active"><%= @product.title %></li>
</ol>
<h2 align="center">Gestione Prodotti</h2>
<div class="row">
  <div class="col-md-8">
    <p class="lead">Dettagli prodotto
    </p>
  </div>

</div>
<div class="container">
  <p class="lead">Prodotto</p>


  <div class="row">
    <div class="col-md-8"><p>
      <strong>Title:</strong>
      <%= @product.title %>
    </p>

      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>

      <p>
        <strong>Image url:</strong>
        <%= @product.image_url %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= number_to_currency(@product.price, :unit => "€") %>
      </p>

      <%= link_to 'Edit', admin_product_edit_path(@product), :class => "btn btn-success btn-xs" %>
      <%= link_to 'Back', admin_products_path, :class => "btn btn-default btn-xs" %>
    </div>
    <div class="col-md-4"></div>
  </div>


</div>

app/views/admin/show_user.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Amministrazione", admin_index_path %></li>
  <li><%= link_to "Utenti", admin_users_path %></li>
  <li class="active"><%= @user.name %></li>
</ol>
<h2 align="center">Gestione Utenti</h2>
<div class="row">
  <div class="col-md-8">
    <p class="lead">Dettagli utente
    </p>
  </div>

</div>
<div class="container">
  <p class="lead">Utenti</p>


  <div class="row">
    <div class="col-md-8">
      <div class="container">
        <p class="row">
          <strong>Nome:</strong>
          <%= @user.name %>
        </p>

        <p class="row">
          <strong>Email:</strong>
          <%= @user.email %>
        </p>

        <p class="row">
          <strong>Ultimo accesso:</strong>
          <%= @user.last_sign_in_at %>
        </p>


        <p class="row">
          <strong>Ultimo ip accesso:</strong>
          <%= @user.last_sign_in_ip %>
        </p>


        <p class="row">
          <strong>Numero ordini</strong>
          <%= @ordersNum %>
        </p>


      </div>

      <%= link_to 'Indietro', admin_users_path, :class => "btn btn-default btn-xs" %>
    </div>
    <div class="col-md-4"></div>
  </div>


</div>

app/views/admin/users.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Amministrazione", admin_index_path %></li>
  <li class="active">Utenti</li>
</ol>
<h2 align="center">Gestione Utenti</h2>
<div class="row">
  <div class="col-md-8">
    <p class="lead">Benvenuto nella pagina di gestione degli utenti
    </p>
  </div>

</div>


<div class="container">
  <p class="lead">Ordini</p>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', admin_user_show_path(user), :class => "btn btn-primary btn-xs" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

</div>