config/routes.rb
Rails.application.routes.draw do

  get 'admin/show_product/:id', to: 'admin#show_product' , as: 'admin_product_show'
  get 'admin/edit_product/:id', to: 'admin#edit_product' , as: 'admin_product_edit'

  get 'admin/new_product', to: 'admin#new_product' , as: 'admin_product_new'

  get 'admin/show_order/:id', to: 'admin#show_order' , as: 'admin_order_show'

  get 'admin/show_user/:id', to: 'admin#show_user' , as: 'admin_user_show'

  get 'errors/404'

  get 'errors/500'

  get 'errors/403'

  get 'admin/index'

  get 'admin/products'

  get 'admin/users'

  get 'admin/orders'

  get 'home/index'

  get 'home/about'

  get 'store/index'

  resources :products

  resources :orders

  resources :line_items

  resources :carts

  root :to => 'home#index'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :products do
    get :who_bought, on: :member
  end

end

app/views/shared/_header.html.erb
<title>Europa Sport</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class= "navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Europa Store", root_path, :class=> "navbar-brand" %>
      <ul class="nav navbar-nav">

        <li><%= link_to "Store" , "/store/index" %></li>
      </ul>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
            <li><%= link_to "Contatti" , home_about_path %></li>
            <li id="fat-menu" class="dropdown">

              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <% if current_user.name? %>
                    <%= current_user.name %> <b class="caret"></b>
                <% else %>
                    <%= current_user.email %> <b class="caret"></b>
                <% end %>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profilo", edit_user_registration_path %></li>
                <li><%= link_to "Ordini", orders_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Disconnetti", destroy_user_session_path, :method => :delete %>
                </li>
                <% if current_user.admin == 1%>
                    <li>
                    <%= link_to "Amministrazione", admin_index_path %>
                    </li>
                <% end %>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Accedi", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_admin.html.erb
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class= "navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Europa Store - Amministrazione", admin_index_path, :class=> "navbar-brand" %>
      <ul class="nav navbar-nav">

        <li><%= link_to "Prodotti" ,admin_products_path %></li>
        <li><%= link_to "Utenti" , admin_users_path %></li>
        <li><%= link_to "Ordini" , admin_orders_path %></li>
      </ul>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profilo", edit_user_registration_path %></li>
                <li><%= link_to "Home", root_path %></li>

                <li class="divider"></li>
                <li>
                  <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                </li>
                <% if current_user.admin==1 %>
                    <li>
                      <%= link_to "Amministrazione", admin_index_path %>
                    </li>
                <% end %>

              </ul>
            </li>

        <% else %>
            <li><%= link_to "Accedi", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_noauth.html.erb
<div class="jumbotron">
  <h1>Hey!!! </h1>
  <p>Devi accedere per poter vedere questa pagina</p>
  <p><%= link_to "Sign in", new_user_session_path ,:class => "btn btn-primary btn-lg" %></p>
</div>