config/routes.rb
Rails.application.routes.draw do

  get 'admin/show_product/:id', to: 'admin#show_product' , as: 'admin_product_show'
  get 'admin/edit_product/:id', to: 'admin#edit_product' , as: 'admin_product_edit'

  get 'admin/new_product', to: 'admin#new_product' , as: 'admin_product_new'

  get 'admin/show_order/:id', to: 'admin#show_order' , as: 'admin_order_show'

  get 'admin/show_user/:id', to: 'admin#show_user' , as: 'admin_user_show'

  get 'errors/404'

  get 'errors/500'

  get 'errors/403'

  get 'admin/index'

  get 'admin/products'

  get 'admin/users'

  get 'admin/orders'

  get 'home/index'

  get 'home/about'

  get 'store/index'

  resources :products

  resources :orders

  resources :line_items

  resources :carts

  root :to => 'home#index'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :products do
    get :who_bought, on: :member
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  #AD UN CARRELLO POSSO ASSOCIARE PIÙ RIGHE D'ORDINE
  #INOLTRE CON LA CHIAMATA DESTROY LE RIGHE DIPENDONO DAL CARRELLO, SE DISTRUGGO IL CARRELLO DISTRUGGO ANCHE LE RIGHE
  has_many :line_items, dependent: :destroy

  #METODO CHE VERIFICA SE IL PRODOTTO È GIÀ PRESENTE NEL CARRELLO, IN MODO DA INCREMENTARNE IL NUMERO
  def add_product(product_id)
    #IL METODO find_by RESTITUISCE UN OGGETTO PRODUCT OPPURE null
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  #METODO CHE CALCOLA IL PREZZO TOTALE DEGLI ARTICOLI DEL CARRELLO
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  #INTERCETTA L'ECCEZIONE SOLLEVATA DA cart.find()
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Carrello creato con successo!' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Carrello modificato con successo!' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
     @cart.destroy if @cart.id == session[:cart_id]
     session[:cart_id] = nil
      respond_to do |format|
      #UNA VOLTA ELIMINATO IL CARRELLO VERREMO RIPORTATI ALLA PAGINA DEL CATALOGO
      format.html { redirect_to store_index_path, notice: 'Carrello svuotato con successo!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

  #SERVE PER GESTIRE LE RICHIESTE DI ERRORE NEL CASO CHE SI SELEZIONI UNCARRELLO NON VALIDO
  def invalid_cart
    #UTILIZIAMO IL LOGGER PER SALVARE UN MESSAGGIO DI ERRORE
    logger.error "Attempt to access invalid cart #{params[:id]}"
    #REINDIRIZIAMO L'UTENTE NELLA PAGINA DEL CATALOGO
    redirect_to store_index_path, notice: 'Invalid cart'
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<!--CON LA PRIMA RIGA DI CODICE IL CARRELLO NON VERRÀ VISUALIZZATO NEL CASO SIA VUOTO-->
<% unless cart.line_items.empty? %>
    <a href="#" class="list-group-item active">Your Cart</a>
    <table>
      <!--METODO CHE ITERA SU TUTTE LE COLLEZIONI CHE GLI VENGONO PASSATE-->
      <%= render(cart.line_items) %>
      <a href="#" class="list-group-item" align="right">Total:
        <span class="badge" align="right"><%= number_to_currency(cart.total_price, :unit => "€")%></span>
      </a>
      <li class="list-group-item">
        <div class="row">
          <div class="col-md-8" align="right">
            <%= link_to 'Empty cart', cart,  class:"btn btn-default", method: :delete,
                          data: { confirm: 'Are you sure?' } %>
          </div>
          <div class="col-md-4" align="left">
            <%= link_to "Checkout", new_order_path, class:"btn btn-danger", method: :get %>
          </div>
        </div>
      </li>
    </table>
<% end %>
<br>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

  <%= render @cart %>