config/routes.rb
Rails.application.routes.draw do

  get 'admin/show_product/:id', to: 'admin#show_product' , as: 'admin_product_show'
  get 'admin/edit_product/:id', to: 'admin#edit_product' , as: 'admin_product_edit'

  get 'admin/new_product', to: 'admin#new_product' , as: 'admin_product_new'

  get 'admin/show_order/:id', to: 'admin#show_order' , as: 'admin_order_show'

  get 'admin/show_user/:id', to: 'admin#show_user' , as: 'admin_user_show'

  get 'errors/404'

  get 'errors/500'

  get 'errors/403'

  get 'admin/index'

  get 'admin/products'

  get 'admin/users'

  get 'admin/orders'

  get 'home/index'

  get 'home/about'

  get 'store/index'

  resources :products

  resources :orders

  resources :line_items

  resources :carts

  root :to => 'home#index'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :products do
    get :who_bought, on: :member
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  #IN QUESTO MODO DICHIARO CHE CI SONO DELLE RELAZIONI
  has_many :line_items, :dependent => :destroy
  has_many :orders, through: :line_items, :dependent => :destroy
  #before_destroy :ensure_not_referenced_by_any_line_item


  #OGNI FORM DEVE CONTENERE QUALCOSA PRIMA DI POTER AGGIUNGERE
  validates :title, :description, :image_url, presence: true
  #CONTROLLA L'UNITICOTÀ DEL TITOLO
  validates :title, uniqueness: true
  #CONTROLLA CHE L'URL DELL'IMMAGINE FINISCA CON GIF, JPG, PNG
  #CON LA FUNZIONE allow_blank eviteremo che siano visualizzati più messaggi di errore
  validates :image_url, allow_blank: true, format: {
      with:   %r{\.(gif|jpg|png)\Z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'
  }
  #CONTROLLO CHE IL PREZZO SIA SEMPRE UN NUMERO POSITIVO MAGGIORE DI 0.01
  validates :price, numericality: {greater_than_or_equal_to: 0.01}


  #STO CREANDO UN METODO HOOK CHE VIENE CHIAMATO IN UN MOMENTO DI VITA SPECIFICO DELL'OGGETTO
  #VIENE CHIAMATO PER EVITARE DI ELIMINARE DAL DATABASE I PRODOTTI CHE SONO SEGNATI COME RIGHE D'ORDINE
  private

  # Assicuratevi che non esistano righe d'ordine che fanno riferimento
  # a questo prodotto
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  #VERIFICANO QUANDO IL CONTENUTO È STATO MODIFICATO PER L'ULTIMA VOLTA
  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <% @products.each do |product| %>
      <!--ALTERNA I COLORI DELLE RIGHE CON IL METODO CYCLE-->
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <%= image_tag(product.image_url, class: 'list_image') %>
        </td>
        <td class="list_description">
          <dl>
            <dt><%= product.title %></dt>
            <!--VISUALIZZA SOLO I PRIMI 80 CARATTERI DELLA DESCRIZIONE-->
            <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
          </dl>
        </td>
        <td class="list_actions">
          <%= link_to 'Show', product %><br/>
          <%= link_to 'Edit', edit_product_path(product) %><br/>
          <!--VISUALIZZA UNA FINESTRA DI DIALOGO PER CONFERMARE LA CANCELLAZIONE DEL PRODOTTO-->
          <%= link_to 'Destroy', product, method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
</table>
<br />
<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% if user_signed_in? %>
    <ol class="breadcrumb">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Store", store_index_path %></li>
      <li class="active"><%= @product.title %></li>
    </ol>
    <div class="row">
      <div class="col-md-8">
        <p class="lead">Dettagli prodotto
        </p>
      </div>

    </div>
    <div class="container">
      <p class="lead">Prodotto</p>

      <div class="row">
        <div class="col-md-8">
          <div class="thumbnail">
          <div class="row">
              <div class="col-md-3">
                <br>
                <%= image_tag( @product.image_url, :class => "img-rounded img-responsive")%>
              </div>
              <div class="col-md-9">
                <div class="caption">
                  <h3>
                    <%= @product.title %>
                  </h3>
                  <p>
                    <strong>Descrizione:</strong>
                    <%= @product.description %>
                  </p>
                  <p>
                    <strong>Prezzo:</strong>
                    <%= number_to_currency(@product.price, :unit => "€") %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4"></div>
      </div>




    </div>
<% else %>
    <script type="text/javascript">
        window.location.href = "../errors/404"  // put your correct path in a string here
    </script>
<% end %>